print("5.grupa")
print("Vineta Tomsone")
print("GitHub konts: vinetat")
print("e-pasts: vineta.tomsone@liepaja.edu.lv")
print("Hobijs: kalnos kāpšana, kas nu jau 2 gadus nav iespējams, bet viss vēl var būt!")

print("Te Kalvis kaut ko pierakstījis klāt")

print("Sveiciens no Sandras :)")
print("Sandra")
print("Vēl viena Sanadras rindiņa")

print("Skolens1")
print("Skolens1 pieraksta jaunas rindinas")
print("Skkolens1 grib pārbaudīt, vai skolotajs sanems so programmas kodu")
print("Skolens1 palaboja kodu")
print("Parbauda, pierakstot jaunu rindu")
print("Skatīsimies, ka darbojas versiju kontrole")
print("Skolotaja atbilde: Skolens1 zars ir pievienots pārējai programmai")
print("Skolotaja atbilde: Skolens1 ir visu izdarījis pareizi")
