print("5.grupa")
print("Vineta Tomsone")
print("GitHub konts: vinetat")
print("e-pasts: vineta.tomsone@liepaja.edu.lv")
print("Hobijs: kalnos kāpšana, kas nu jau 2 gadus nav iespējams, bet viss vēl var būt!")

print("Te Kalvis kaut ko pierakstījis klāt")
print("Skolens1")
print("Parbauda, pierakstot jaunu rindu")
print("Skatīsimies, ka darbojas versiju kontrole")
